server:
  HTTPPort: 8000
  HTTPSPort: 8442
  Proto: HTTP/1.1
  IsCgi: false
  Workdir: "./statics"
  IPv4: "0.0.0.0"
  IPv6: "::"
  IsDualStack: false
  DeadLine: 10
  IsGzip: true
  CGIDirectories:
    - "cgi-bin"
    - "bin"
  EnableTLS: true
  CertFile: "./certs/server.crt"
  KeyFile: "./certs/server.key"
  ForceIPV4: true

logger:
  LogToFile: true
  FilePath: "./logs"
  WithTime: true